import type { Metadata } from "next";
import { Geist, Geist_Mono,Prompt, Playfair_Display } from "next/font/google";
import "./globals.css";
// import { Prompt, Playfair_Display } from "next/font/google";

const prompt = Prompt({
  weight: ["400", "700"],
  subsets: ["thai", "latin"],
  variable: "--font-body",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-title",
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Happy Valentine's Day, My Love",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${prompt.variable} ${playfair.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
